// Code generated by go-swagger; DO NOT EDIT.

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// IpamVlansDeleteReader is a Reader for the IpamVlansDelete structure.
type IpamVlansDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IpamVlansDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewIpamVlansDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewIpamVlansDeleteNoContent creates a IpamVlansDeleteNoContent with default headers values
func NewIpamVlansDeleteNoContent() *IpamVlansDeleteNoContent {
	return &IpamVlansDeleteNoContent{}
}

/*IpamVlansDeleteNoContent handles this case with default header values.

IpamVlansDeleteNoContent ipam vlans delete no content
*/
type IpamVlansDeleteNoContent struct {
}

func (o *IpamVlansDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /ipam/vlans/{id}/][%d] ipamVlansDeleteNoContent ", 204)
}

func (o *IpamVlansDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
