// Code generated by go-swagger; DO NOT EDIT.

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/proelbtn/proxmox2netbox/models"
)

// IpamIPAddressesReadReader is a Reader for the IpamIPAddressesRead structure.
type IpamIPAddressesReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IpamIPAddressesReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIpamIPAddressesReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewIpamIPAddressesReadOK creates a IpamIPAddressesReadOK with default headers values
func NewIpamIPAddressesReadOK() *IpamIPAddressesReadOK {
	return &IpamIPAddressesReadOK{}
}

/*IpamIPAddressesReadOK handles this case with default header values.

IpamIPAddressesReadOK ipam Ip addresses read o k
*/
type IpamIPAddressesReadOK struct {
	Payload *models.IPAddress
}

func (o *IpamIPAddressesReadOK) Error() string {
	return fmt.Sprintf("[GET /ipam/ip-addresses/{id}/][%d] ipamIpAddressesReadOK  %+v", 200, o.Payload)
}

func (o *IpamIPAddressesReadOK) GetPayload() *models.IPAddress {
	return o.Payload
}

func (o *IpamIPAddressesReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IPAddress)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
