// Code generated by go-swagger; DO NOT EDIT.

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// IpamAggregatesDeleteReader is a Reader for the IpamAggregatesDelete structure.
type IpamAggregatesDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IpamAggregatesDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewIpamAggregatesDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewIpamAggregatesDeleteNoContent creates a IpamAggregatesDeleteNoContent with default headers values
func NewIpamAggregatesDeleteNoContent() *IpamAggregatesDeleteNoContent {
	return &IpamAggregatesDeleteNoContent{}
}

/*IpamAggregatesDeleteNoContent handles this case with default header values.

IpamAggregatesDeleteNoContent ipam aggregates delete no content
*/
type IpamAggregatesDeleteNoContent struct {
}

func (o *IpamAggregatesDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /ipam/aggregates/{id}/][%d] ipamAggregatesDeleteNoContent ", 204)
}

func (o *IpamAggregatesDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
