// Code generated by go-swagger; DO NOT EDIT.

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/proelbtn/proxmox2netbox/models"
)

// IpamRirsPartialUpdateReader is a Reader for the IpamRirsPartialUpdate structure.
type IpamRirsPartialUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IpamRirsPartialUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIpamRirsPartialUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewIpamRirsPartialUpdateOK creates a IpamRirsPartialUpdateOK with default headers values
func NewIpamRirsPartialUpdateOK() *IpamRirsPartialUpdateOK {
	return &IpamRirsPartialUpdateOK{}
}

/*IpamRirsPartialUpdateOK handles this case with default header values.

IpamRirsPartialUpdateOK ipam rirs partial update o k
*/
type IpamRirsPartialUpdateOK struct {
	Payload *models.RIR
}

func (o *IpamRirsPartialUpdateOK) Error() string {
	return fmt.Sprintf("[PATCH /ipam/rirs/{id}/][%d] ipamRirsPartialUpdateOK  %+v", 200, o.Payload)
}

func (o *IpamRirsPartialUpdateOK) GetPayload() *models.RIR {
	return o.Payload
}

func (o *IpamRirsPartialUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RIR)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
