// Code generated by go-swagger; DO NOT EDIT.

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/proelbtn/proxmox2netbox/models"
)

// IpamRirsUpdateReader is a Reader for the IpamRirsUpdate structure.
type IpamRirsUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IpamRirsUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIpamRirsUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewIpamRirsUpdateOK creates a IpamRirsUpdateOK with default headers values
func NewIpamRirsUpdateOK() *IpamRirsUpdateOK {
	return &IpamRirsUpdateOK{}
}

/*IpamRirsUpdateOK handles this case with default header values.

IpamRirsUpdateOK ipam rirs update o k
*/
type IpamRirsUpdateOK struct {
	Payload *models.RIR
}

func (o *IpamRirsUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /ipam/rirs/{id}/][%d] ipamRirsUpdateOK  %+v", 200, o.Payload)
}

func (o *IpamRirsUpdateOK) GetPayload() *models.RIR {
	return o.Payload
}

func (o *IpamRirsUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RIR)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
