// Code generated by go-swagger; DO NOT EDIT.

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/proelbtn/proxmox2netbox/models"
)

// IpamRolesPartialUpdateReader is a Reader for the IpamRolesPartialUpdate structure.
type IpamRolesPartialUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IpamRolesPartialUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIpamRolesPartialUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewIpamRolesPartialUpdateOK creates a IpamRolesPartialUpdateOK with default headers values
func NewIpamRolesPartialUpdateOK() *IpamRolesPartialUpdateOK {
	return &IpamRolesPartialUpdateOK{}
}

/*IpamRolesPartialUpdateOK handles this case with default header values.

IpamRolesPartialUpdateOK ipam roles partial update o k
*/
type IpamRolesPartialUpdateOK struct {
	Payload *models.Role
}

func (o *IpamRolesPartialUpdateOK) Error() string {
	return fmt.Sprintf("[PATCH /ipam/roles/{id}/][%d] ipamRolesPartialUpdateOK  %+v", 200, o.Payload)
}

func (o *IpamRolesPartialUpdateOK) GetPayload() *models.Role {
	return o.Payload
}

func (o *IpamRolesPartialUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Role)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
