// Code generated by go-swagger; DO NOT EDIT.

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/proelbtn/proxmox2netbox/models"
)

// IpamAggregatesReadReader is a Reader for the IpamAggregatesRead structure.
type IpamAggregatesReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IpamAggregatesReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIpamAggregatesReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewIpamAggregatesReadOK creates a IpamAggregatesReadOK with default headers values
func NewIpamAggregatesReadOK() *IpamAggregatesReadOK {
	return &IpamAggregatesReadOK{}
}

/*IpamAggregatesReadOK handles this case with default header values.

IpamAggregatesReadOK ipam aggregates read o k
*/
type IpamAggregatesReadOK struct {
	Payload *models.Aggregate
}

func (o *IpamAggregatesReadOK) Error() string {
	return fmt.Sprintf("[GET /ipam/aggregates/{id}/][%d] ipamAggregatesReadOK  %+v", 200, o.Payload)
}

func (o *IpamAggregatesReadOK) GetPayload() *models.Aggregate {
	return o.Payload
}

func (o *IpamAggregatesReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Aggregate)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
