// Code generated by go-swagger; DO NOT EDIT.

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// IpamPrefixesDeleteReader is a Reader for the IpamPrefixesDelete structure.
type IpamPrefixesDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IpamPrefixesDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewIpamPrefixesDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewIpamPrefixesDeleteNoContent creates a IpamPrefixesDeleteNoContent with default headers values
func NewIpamPrefixesDeleteNoContent() *IpamPrefixesDeleteNoContent {
	return &IpamPrefixesDeleteNoContent{}
}

/*IpamPrefixesDeleteNoContent handles this case with default header values.

IpamPrefixesDeleteNoContent ipam prefixes delete no content
*/
type IpamPrefixesDeleteNoContent struct {
}

func (o *IpamPrefixesDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /ipam/prefixes/{id}/][%d] ipamPrefixesDeleteNoContent ", 204)
}

func (o *IpamPrefixesDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
